---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-k8s-operator-deployment
  labels:
    app.kubernetes.io/name: spark-k8s-operator
    app.kubernetes.io/instance: spark-k8s-operator
    app.kubernetes.io/version: "0.5.0-nightly"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: spark-k8s-operator
      app.kubernetes.io/instance: spark-k8s-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spark-k8s-operator
        app.kubernetes.io/instance: spark-k8s-operator
    spec:
      serviceAccountName: spark-k8s-operator-serviceaccount
      securityContext: {}
      containers:
        - name: spark-k8s-operator
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: false
            seccompProfile:
              type: RuntimeDefault
          image: "docker.stackable.tech/stackable/spark-k8s-operator:0.5.0-nightly"
          imagePullPolicy: IfNotPresent
          resources: {}
          volumeMounts:
            - mountPath: /etc/stackable/spark-k8s-operator/config-spec
              name: config-spec
      volumes:
        - name: config-spec
          configMap:
            name: spark-k8s-operator-configmap
