[package]
authors = ["Stackable GmbH <info@stackable.de>"]
description = "Stackable Kubernetes Operator for Apache Spark"
edition = "2021"
license = "OSL-3.0"
name = "stackable-spark-k8s-operator"
repository = "https://github.com/stackabletech/spark-k8s-operator"
version = "0.2.0-nightly"

[dependencies]
stackable-operator = { git = "https://github.com/stackabletech/operator-rs.git", tag="0.19.0" }
stackable-spark-k8s-crd = { path = "../crd" }
anyhow = "1.0"
clap = { version = "3.1", features = ["derive"] }
futures = "0.3"
serde = "1.0"
serde_yaml = "0.8"
snafu = "0.7"
strum = { version = "0.24.0", features = ["derive"] }
tokio = { version = "1.19", features = ["macros", "rt-multi-thread"] }
tracing = "0.1"
tracing-futures = { version = "0.2", features = ["futures-03"] }

[build-dependencies]
built = { version =  "0.5", features = ["chrono", "git2"] }
stackable-operator = { git = "https://github.com/stackabletech/operator-rs.git", tag="0.19.0" }
stackable-spark-k8s-crd = { path = "../crd" }
