---
blank_issues_enabled: true
contact_links:
  - name: Feature request
    about: ğŸš€ Suggest an idea for this project
    url: https://github.com/orgs/stackabletech/discussions/new?category=ideas
  - name: ğŸ™‹ğŸ¾ Question
    about: Use this to ask a question about this project
    url: https://github.com/orgs/stackabletech/discussions/new?category=general
  - name: Other issue
    about: Open an issue that doesn't fit any other category
    url: https://github.com/stackabletech/spark-k8s-operator/issues/new
