---
apiVersion: spark.stackable.tech/v1alpha1
kind: SparkApplication
metadata:
  name: pyspark-pi # <1>
  namespace: default
spec:
  sparkImage: # <2>
    productVersion: 3.5.8
  mode: cluster # <3>
  mainApplicationFile: local:///stackable/spark/examples/src/main/python/pi.py # <4>
  job: # <5>
    config:
      resources:
        cpu:
          min: "1"
          max: "2"
        memory:
          limit: "1Gi"
  driver: # <6>
    config:
      resources:
        cpu:
          min: "1"
          max: "2"
        memory:
          limit: "1Gi"
  executor: # <7>
    replicas: 1
    config:
      resources:
        cpu:
          min: "1"
          max: "2"
        memory:
          limit: "1Gi"
