---
name: pre-commit

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN_VERSION: "1.82.0"
  HADOLINT_VERSION: "v2.12.0"
  PYTHON_VERSION: "3.12"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Install host dependencies
        uses: awalsh128/cache-apt-pkgs-action@5902b33ae29014e6ca012c5d8025d4346556bd40 # v1.4.3
        with:
          packages: protobuf-compiler krb5-user libkrb5-dev libclang-dev liblzma-dev libssl-dev pkg-config apt-transport-https
          version: ubuntu-latest
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: stackabletech/actions/run-pre-commit@5b66858af3597c4ea34f9b33664b8034a1d28427 # v0.3.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          rust: ${{ env.RUST_TOOLCHAIN_VERSION }}
          hadolint: ${{ env.HADOLINT_VERSION }}
